In [1]:
""".Write a NumPy function to extract elements
in specific order from a given 2D array based on indices 
provided in another array"""

'.Write a NumPy function to extract elements\nin specific order from a given 2D array based on indices \nprovided in another array'

In [4]:
import numpy as np
def extract(idx):
    return arr[idx[:,0],idx[:,1]]
arr=np.arange(12).reshape(4,3)
print(arr)
idx=np.array([[1,2],[0,1]])
extract(idx)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([5, 1])

In [7]:
arr[indx[:,0],indx[:,1]]

array([5, 1])