In [3]:
""" Develop a NumPy function that extracts specific
elements from a 3D array using indices provided in three 
separate arrays for each dimension"""
import numpy as np
def extract(arr,dim1_idx,dim2_idx,dim3_idx):
    return arr[dim1_idx,dim2_idx,dim3_idx]
arr=np.arange(24).reshape(2,4,3)
print(arr)
dim1_idx=np.array([0,1])
dim2_idx=np.array([0,2])
dim3_idx=np.array([0,2])
extract(arr,dim1_idx,dim2_idx,dim3_idx)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


array([ 0, 20])

In [10]:

import numpy as np
arr=np.arange(24).reshape(2,4,3)
print(arr)
arr[[0,1],[1,3],[1,2]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


array([ 4, 23])