In [15]:
""". Write a NumPy function that returns elements from
an array where both two conditions are satisfied 
using boolean indexing"""
import numpy as np
def elements(cond1,cond2):
    return arr[np.logical_and(cond1,cond2)]
arr=np.arange(24).reshape(2,4,3)
cond1=arr>1
cond2=arr<5
elements(cond1,cond2)
    

array([2, 3, 4])

In [14]:
import numpy as np
arr=np.arange(24).reshape(2,4,3)
print(arr)
arr[arr>2 & arr<5]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [8]:
arr=np.arange(24).reshape(2,4,3)
print(arr)
np.where(arr>20)#idx

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


(array([1, 1, 1]), array([3, 3, 3]), array([0, 1, 2]))