In [3]:
""" Create a NumPy function that extracts elements 
from a 2D array using row and column indices provided 
in separate arrays"""
import numpy as np
def ele(row,col):
    return arr[row,col]
arr=np.arange(12).reshape(4,3)
print(arr)
row=np.array([1,2])
col=np.array([0,1])
ele(row,col)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([3, 7])