In [3]:
""" Given an array arr of shape (3, 3), add a scalar 
value of 5 to each element using NumPy broadcasting"""
import numpy as np
arr=np.arange(9).reshape(3,3)
v=5#scalar value is bradcasted to the shape og =f the arr
print(arr+v)


[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
