In [15]:
"""Consider two arrays arr1 of shape (1, 3) and arr2 of
shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting."""
import numpy as np
arr1=np.arange(3).reshape(1,3)#doubt
print(arr1)
arr2=np.arange(12).reshape(3,4)
print(arr2)
r=arr1.T * arr2
print(r)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]
