In [2]:
""" Given a 1D array arr1 of shape (1, 4) and a 2D
\array arr2 of shape (4, 3), add arr1 to each row of arr2 
using NumPy broadcasting."""
import numpy as np
arr1=np.arange(4).reshape(1,4)#doubt
print(arr1)
arr2=np.arange(12).reshape(4,3)
print(arr2)
arr1.T+arr2


[[0 1 2 3]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])