In [22]:
""". Create a NumPy array `arr1` with random integers and
another array `arr2`with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`"""
import numpy as np
arr1=np.random.randint(1,10,size=(1,10))
print(arr1)
arr2=np.arange(1,11).reshape(1,10)
print(arr2)
print(arr1+arr2)

[[6 2 6 5 7 1 1 7 2 7]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 7  4  9  9 12  7  8 15 11 17]]


In [15]:
"""arr1=np.random.random(size=(1,10))
print(arr1)
arr2=np.random.randint(1,10,size=(1,10))
print(arr2)"""

'arr1=np.random.random(size=(1,10))\nprint(arr1)\narr2=np.random.randint(1,10,size=(1,10))\nprint(arr2)'