In [2]:
""" Create two matrices and perform matrix 
multiplication using NumPy's `dot` function."""
import numpy as np
matrix1=np.matrix([1,2,34])
matrix2=np.matrix([5,6,78]).reshape(3,1)
print(matrix1)
print(matrix2)
np.dot(matrix1,matrix2)


[[ 1  2 34]]
[[ 5]
 [ 6]
 [78]]


matrix([[2669]])