In [10]:
""" Create a 2D NumPy array `matrix` of shape (3, 3) 
with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe 
if it changes the original `matrix`."""
import numpy as np
matrix=np.random.randint(9,size=(3,3))
view_slice=matrix[0,:]
view_slice[1]=78

print(view_slice)
print(matrix)
if np.array_equal(matrix[0,:],view_slice):
    print("yes it is affecting")
else:
    print("no")



[ 3 78  4]
[[ 3 78  4]
 [ 4  3  6]
 [ 2  0  7]]
yes it is affecting
