In [6]:
"""Create a NumPy array `array_a` of shape (4, 3) with 
sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of
\5 to view_b. Check if it alters the original `array_a`."""
import numpy as np
array_a=np.arange(1,13).reshape(4,3)
view_b=array_a[0,:]
view_b+=5
print(view_b)
print(array_a)
if np.array_equal(array_a[0,:],view_b):
    print("yes it is affecting")
else:
    print("no")


[6 7 8]
[[ 6  7  8]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
yes it is affecting
