In [17]:
""". Create a NumPy array `orig_array` of shape (2, 4) 
with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. 
Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array`"""
import numpy as np
orig_array=np.arange(1,9).reshape(2,4)
reshaped_view=orig_array.reshape(4,2)
reshaped_view[0,1]=99
print(reshaped_view)
print(orig_array)
for i in range(len(reshaped_view)):
    for j in range(len(reshaped_view[0])):
        if reshaped_view[i][j] in orig_array:
            continue
        else:
            print("no")
            break
print("yes")



[[ 1 99]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
[[ 1 99  3  4]
 [ 5  6  7  8]]
yes


In [15]:
r=orig_array.reshape(4,2)
print(r)
if 1 in r:
    print("h")
#np.items(r)
len(r[)

[[ 1 99]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
h


2