In [6]:
"""8. Design a function item_size_info that takes a NumPy 
array as
input and returns the item size and total size in bytes."""
import numpy as np
def item_size_info(arr):
    return arr.itemsize,arr.nbytes
arr=np.arange(9).reshape(3,3)
print(arr)
item_size,total_size=item_size_info(arr)
print("item size is ",item_size)
print("total size is ",total_size)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
item size is  8
total size is  72
