In [1]:
""" Create a NumPy array `data` of shape (3, 4) with 
random integers. Extract a copy `data_copy` of elements
greater than 5. Modify an element in `data_copy`
and verify if it affects the original `data`."""
import numpy as np
data=np.random.randint(13,size=(3,4))
print("before")
print("data",data)
data_copy=data[data>5]
print("data_copy",data_copy)
data_copy[0]=99
print("after")
print("data",data)
print("data_cpy",data_copy)





before
data [[ 8 10  6  2]
 [ 4  6  8  2]
 [11 12 10 12]]
data_copy [ 8 10  6  6  8 11 12 10 12]
after
data [[ 8 10  6  2]
 [ 4  6  8  2]
 [11 12 10 12]]
data_cpy [99 10  6  6  8 11 12 10 12]
