In [3]:
""" Create two matrices A and B of identical shape 
containing integers and perform addition and subtraction 
operations between them"""
import numpy as np
A=np.arange(12).reshape(4,3)
B=np.arange(12,24).reshape(4,3)
print("A is ",A)
print("B is",B)
print("A+B \n",A+B)
print("A-B",A-B)


A is  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
B is [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
A+B 
 [[12 14 16]
 [18 20 22]
 [24 26 28]
 [30 32 34]]
A-B [[-12 -12 -12]
 [-12 -12 -12]
 [-12 -12 -12]
 [-12 -12 -12]]
