In [3]:
""" Generate two matrices `C` (3x2) and `D` (2x4) and 
perform matrix multiplication"""
import numpy as np
c=np.arange(6).reshape(3,2)
d=np.arange(8).reshape(2,4)
print(c,d)
print(c@d)

[[0 1]
 [2 3]
 [4 5]] [[0 1 2 3]
 [4 5 6 7]]
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
